name: Build and Run with Docker

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t urbanmotion .

    - name: Run UrbanMotion in Docker
      run: |
        docker run --rm urbanmotion

    - name: Clean up
      run: |
        docker rmi urbanmotion
